/* 🤖 this file was generated by svg-to-ts */
export const myIconBook: {
  name: "book";
  data: string;
} = {
    name: "book",
    data: "<svg width=\"24\" height=\"24\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M20.477 17.671a.257.257 0 0 1-.238-.264l-.499-.037.498.041c.012-.14.012-.288.012-.402V7c0-.901-.042-1.655-.171-2.273-.131-.623-.359-1.145-.758-1.544-.398-.4-.92-.628-1.543-.76-.619-.13-1.374-.173-2.278-.173h-7c-.904 0-1.66.042-2.278.173-.624.132-1.145.36-1.543.76-.399.4-.627.92-.758 1.544C3.791 5.345 3.75 6.1 3.75 7v11c0 .134-.116.25-.25.25a.256.256 0 0 1-.25-.25V7c0-2.188.34-3.441 1.075-4.175C5.059 2.09 6.312 1.75 8.5 1.75h7c2.188 0 3.441.34 4.175 1.075.734.734 1.075 1.987 1.075 4.175v10c0 .16 0 .295-.009.435-.011.139-.145.245-.264.236Z\" fill=\"#292D32\" stroke=\"currentColor\"/><path d=\"M20.25 15.75v-.5H6.35a2.6 2.6 0 0 0-2.6 2.6v.65A3.248 3.248 0 0 0 7 21.75h10a3.248 3.248 0 0 0 3.25-3.25v-2.75ZM17 22.25H7a3.76 3.76 0 0 1-3.75-3.75v-.65c0-1.713 1.395-3.1 3.1-3.1H20.5c.134 0 .25.116.25.25v3.5A3.76 3.76 0 0 1 17 22.25ZM16 7.25H8A.256.256 0 0 1 7.75 7c0-.134.116-.25.25-.25h8c.134 0 .25.116.25.25s-.116.25-.25.25ZM13 10.75H8a.256.256 0 0 1-.25-.25c0-.134.116-.25.25-.25h5c.134 0 .25.116.25.25s-.116.25-.25.25Z\" fill=\"#292D32\" stroke=\"currentColor\"/></svg>"
};
export const myIconCalendar: {
  name: "calendar";
  data: string;
} = {
    name: "calendar",
    data: "<svg width=\"24\" height=\"24\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M8 2v3M16 2v3M3.5 9.09h17M21 8.5V17c0 3-1.5 5-5 5H8c-3.5 0-5-2-5-5V8.5c0-3 1.5-5 5-5h8c3.5 0 5 2 5 5Z\" stroke=\"currentColor\" stroke-width=\"1.5\" stroke-miterlimit=\"10\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M15.695 13.7h.009M15.695 16.7h.009M11.995 13.7h.01M11.995 16.7h.01M8.294 13.7h.01M8.294 16.7h.01\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>"
};
export const myIconChevronLeft: {
  name: "chevron_left";
  data: string;
} = {
    name: "chevron_left",
    data: "<svg width=\"24\" height=\"24\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path fill-rule=\"evenodd\" clip-rule=\"evenodd\" d=\"M13.362 7a.996.996 0 0 0-.719.305l-3.863 4a1 1 0 0 0 .013 1.402l4 4a.999.999 0 1 0 1.414-1.414l-3.305-3.305 3.18-3.293A1 1 0 0 0 13.361 7Z\" fill=\"currentColor\"/></svg>"
};
export const myIconChevronRight: {
  name: "chevron_right";
  data: string;
} = {
    name: "chevron_right",
    data: "<svg width=\"24\" height=\"24\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path fill-rule=\"evenodd\" clip-rule=\"evenodd\" d=\"M10.5 7a.999.999 0 0 0-.707 1.707l3.305 3.305-3.18 3.293a1 1 0 0 0 1.439 1.39l3.862-4a1 1 0 0 0-.012-1.402l-4-4A.997.997 0 0 0 10.5 7Z\" fill=\"currentColor\"/></svg>"
};
export const myIconDashboard: {
  name: "dashboard";
  data: string;
} = {
    name: "dashboard",
    data: "<svg width=\"24\" height=\"24\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M22 8.27V4.23C22 2.64 21.36 2 19.77 2h-4.04c-1.59 0-2.23.64-2.23 2.23v4.04c0 1.59.64 2.23 2.23 2.23h4.04c1.59 0 2.23-.64 2.23-2.23ZM10.5 8.52V3.98C10.5 2.57 9.86 2 8.27 2H4.23C2.64 2 2 2.57 2 3.98v4.53c0 1.42.64 1.98 2.23 1.98h4.04c1.59.01 2.23-.56 2.23-1.97ZM10.5 19.77v-4.04c0-1.59-.64-2.23-2.23-2.23H4.23c-1.59 0-2.23.64-2.23 2.23v4.04C2 21.36 2.64 22 4.23 22h4.04c1.59 0 2.23-.64 2.23-2.23Z\" stroke=\"currentColor\" stroke-width=\"1.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M15 15.5h6M15 19.5h6\" stroke=\"currentColor\" stroke-width=\"1.5\" stroke-linecap=\"round\"/></svg>"
};
export const myIconFolderOpen: {
  name: "folder_open";
  data: string;
} = {
    name: "folder_open",
    data: "<svg width=\"32\" height=\"32\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"m28.08 15.76-.213-.293a4.278 4.278 0 0 0-1.32-1.08 4.544 4.544 0 0 0-2.254-.587h-16.6c-.8 0-1.56.2-2.253.587-.52.28-.987.666-1.373 1.146-.76.974-1.12 2.174-1 3.374l.493 6.226c.173 1.88.4 4.2 4.627 4.2h15.626c4.227 0 4.44-2.32 4.627-4.213l.493-6.2a4.486 4.486 0 0 0-.853-3.16Zm-8.893 7.36H12.8a.936.936 0 0 1-.933-.933c0-.507.413-.934.933-.934h6.387c.52 0 .933.427.933.934 0 .52-.413.933-.933.933Z\" fill=\"currentColor\"/><path opacity=\".4\" d=\"M4.507 15.08c.293-.267.586-.507.933-.693a4.544 4.544 0 0 1 2.253-.587h16.614c.8 0 1.56.2 2.253.587.347.186.653.426.933.706v-2c0-4.76-1.453-6.213-6.213-6.213h-3.173c-.587 0-.6-.013-.947-.467l-1.6-2.146c-.76-.987-1.36-1.6-3.267-1.6H10.72c-4.76 0-6.213 1.453-6.213 6.213V15.08Z\" fill=\"currentColor\"/></svg>"
};
export const myIconLogout: {
  name: "logout";
  data: string;
} = {
    name: "logout",
    data: "<svg width=\"24\" height=\"24\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M17.44 14.62 20 12.06 17.44 9.5M9.76 12.06h10.17M11.76 20c-4.42 0-8-3-8-8s3.58-8 8-8\" stroke=\"currentColor\" stroke-width=\"1.5\" stroke-miterlimit=\"10\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>"
};
export const myIconMain: {
  name: "main";
  data: string;
} = {
    name: "main",
    data: "<svg width=\"37\" height=\"23\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path fill-rule=\"evenodd\" clip-rule=\"evenodd\" d=\"m11.22 1.108-9.38 9.203-1-1.02L10.217.088l1.001 1.02ZM.01 21.433 20.57 1.258l1.002 1.02L1.01 22.455.01 21.434ZM25.741 21.538l9.379-9.202 1 1.02-9.378 9.203-1-1.02ZM36.95 1.213 16.39 21.388l-1.002-1.02L35.95.193l1 1.02Z\" fill=\"#36F\"/></svg>"
};
export const myIconMenu: {
  name: "menu";
  data: string;
} = {
    name: "menu",
    data: "<svg width=\"24\" height=\"24\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path fill-rule=\"evenodd\" clip-rule=\"evenodd\" d=\"M3.948 6h16.103c.522 0 .95.427.95.949v.102a.952.952 0 0 1-.95.949H3.948A.95.95 0 0 1 3 7.051v-.102A.95.95 0 0 1 3.948 6Zm16.103 5H3.948a.95.95 0 0 0-.948.949v.102a.95.95 0 0 0 .948.949h16.103a.952.952 0 0 0 .95-.949v-.102a.952.952 0 0 0-.95-.949Zm0 5H3.948a.95.95 0 0 0-.948.949v.102a.95.95 0 0 0 .948.949h16.103a.952.952 0 0 0 .95-.949v-.102a.952.952 0 0 0-.95-.949Z\" fill=\"currentColor\"/></svg>"
};
export const myIconMessages2: {
  name: "messages_2";
  data: string;
} = {
    name: "messages_2",
    data: "<svg width=\"24\" height=\"24\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"m18.47 16.83.39 3.16c.1.83-.79 1.41-1.5.98l-4.19-2.49c-.46 0-.91-.03-1.35-.09A4.86 4.86 0 0 0 13 15.23c0-2.84-2.46-5.14-5.5-5.14-1.16 0-2.23.33-3.12.91-.03-.25-.04-.5-.04-.76C4.34 5.69 8.29 2 13.17 2S22 5.69 22 10.24c0 2.7-1.39 5.09-3.53 6.59Z\" stroke=\"currentColor\" stroke-width=\"1.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M13 15.23c0 1.19-.44 2.29-1.18 3.16-.99 1.2-2.56 1.97-4.32 1.97l-2.61 1.55c-.44.27-1-.1-.94-.61l.25-1.97C2.86 18.4 2 16.91 2 15.23c0-1.76.94-3.31 2.38-4.23.89-.58 1.96-.91 3.12-.91 3.04 0 5.5 2.3 5.5 5.14Z\" stroke=\"currentColor\" stroke-width=\"1.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>"
};
export const myIconMoreVertical: {
  name: "more_vertical";
  data: string;
} = {
    name: "more_vertical",
    data: "<svg width=\"24\" height=\"24\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path fill-rule=\"evenodd\" clip-rule=\"evenodd\" d=\"M12 7a2 2 0 1 0-.001-4.001A2 2 0 0 0 12 7Zm0 3a2 2 0 1 0 .001 4.001A2 2 0 0 0 12 10Zm-2 9a2 2 0 1 1 4.001.001A2 2 0 0 1 10 19Z\" fill=\"currentColor\"/></svg>"
};
export const myIconNotification: {
  name: "notification";
  data: string;
} = {
    name: "notification",
    data: "<svg width=\"24\" height=\"24\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M12.02 2.91c-3.31 0-6 2.69-6 6v2.89c0 .61-.26 1.54-.57 2.06L4.3 15.77c-.71 1.18-.22 2.49 1.08 2.93 4.31 1.44 8.96 1.44 13.27 0 1.21-.4 1.74-1.83 1.08-2.93l-1.15-1.91c-.3-.52-.56-1.45-.56-2.06V8.91c0-3.3-2.7-6-6-6Z\" stroke=\"currentColor\" stroke-width=\"1.5\" stroke-miterlimit=\"10\" stroke-linecap=\"round\"/><path d=\"M13.87 3.2a6.754 6.754 0 0 0-3.7 0c.29-.74 1.01-1.26 1.85-1.26.84 0 1.56.52 1.85 1.26Z\" stroke=\"currentColor\" stroke-width=\"1.5\" stroke-miterlimit=\"10\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M15.02 19.06c0 1.65-1.35 3-3 3-.82 0-1.58-.34-2.12-.88a3.01 3.01 0 0 1-.88-2.12\" stroke=\"currentColor\" stroke-width=\"1.5\" stroke-miterlimit=\"10\"/></svg>"
};
export const myIconSetting: {
  name: "setting";
  data: string;
} = {
    name: "setting",
    data: "<svg width=\"24\" height=\"24\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M3 9.11v5.77C3 17 3 17 5 18.35l5.5 3.18c.83.48 2.18.48 3 0l5.5-3.18c2-1.35 2-1.35 2-3.46V9.11C21 7 21 7 19 5.65l-5.5-3.18c-.82-.48-2.17-.48-3 0L5 5.65C3 7 3 7 3 9.11Z\" stroke=\"currentColor\" stroke-width=\"1.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M12 15a3 3 0 1 0 0-6 3 3 0 0 0 0 6Z\" stroke=\"currentColor\" stroke-width=\"1.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>"
};
export const myIconTeacher: {
  name: "teacher";
  data: string;
} = {
    name: "teacher",
    data: "<svg width=\"24\" height=\"24\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M10.05 2.53 4.03 6.46c-1.93 1.26-1.93 4.08 0 5.34l6.02 3.93c1.08.71 2.86.71 3.94 0l5.99-3.93c1.92-1.26 1.92-4.07 0-5.33l-5.99-3.93c-1.08-.72-2.86-.72-3.94-.01Z\" stroke=\"currentColor\" stroke-width=\"1.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"m5.63 13.08-.01 4.69c0 1.27.98 2.63 2.18 3.03l3.19 1.06c.55.18 1.46.18 2.02 0l3.19-1.06c1.2-.4 2.18-1.76 2.18-3.03v-4.64M21.4 15V9\" stroke=\"currentColor\" stroke-width=\"1.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>"
};
export type myIcons =
  | "book"
  | "calendar"
  | "chevron_left"
  | "chevron_right"
  | "dashboard"
  | "folder_open"
  | "logout"
  | "main"
  | "menu"
  | "messages_2"
  | "more_vertical"
  | "notification"
  | "setting"
  | "teacher";
export interface MyIcon {
  name: myIcons;
  data: string;
}
export type MyIconNameSubset<T extends Readonly<MyIcon[]>> = T[number]["name"];
export const completeIconSet = [
    myIconBook,
    myIconCalendar,
    myIconChevronLeft,
    myIconChevronRight,
    myIconDashboard,
    myIconFolderOpen,
    myIconLogout,
    myIconMain,
    myIconMenu,
    myIconMessages2,
    myIconMoreVertical,
    myIconNotification,
    myIconSetting,
    myIconTeacher
];
